
"""
Test 50 random cubes
"""

from rubikscubesolvermicropython.cube import RubiksCube333

test_cubes = (
    "RRBBUFBFBRLRRRFRDDURUBFBBRFLUDUDFLLFFLLLLDFBDDDUUBDLUU",
    "UFRUUDRLFLBUFRUDLBDFUFFDBBBRRRDDBFLDLBFDLRLRUFUBRBLLUD",
    "BLLFULDFURBFFRFBBDFLFUFRFURDLDDDUUBLUURRLRRRLUDLDBBBDB",
    "URDFUDUDURRRRRUBBDFBFFFBDDULLRFDLBUBLDLLLRDUFFUBLBFRBL",
    "UFLUURFRRDBDLRBLRRUFFRFDLDBUBDLDULFDBBRLLDUUFFDRLBFBUB",
    "LBDUURFDDRDFDRLBRURFBBFLULDLFLFDBBUFURDLLUURBLDFUBBRFR",
    "DRFBUURDUBFRURLDDFBLRFFBLRFUDLBDFBBDBRDRLLLDFUFLUBURLU",
    "BUUDULFFLUUBLRBDFRUUFBFFULFBBLBDDRDFLRRFLRDURLRDDBRDLB",
    "LRLUUDDLDFFUFRFLBLRURDFUULBBDDBDLFRFFRBBLRRURBBDLBDUFU",
    "DLRUUUBBLBFULRLURFDDUDFDLULDBFDDBBFDLRRBLRUFBFFFUBLRRR",
    "UURRUDUDLUFFFRDLLLBBFUFLDRURUBRDULLBRFRBLBDDBDFFLBRDBF",
    "RLFRULDUDBDUURDBFRLLLDFBDRLRUUFDURFBDBFDLFULBLBFRBBURF",
    "DDDLULBUFUUBFRDLFDRBRBFULUUURBLDRRLLLDUDLRFFFRRFBBFBBD",
    "RURRUBDFUFLFFRBBDULLLUFRBRUUBRUDFLFFBDFLLRBLLDBDDBDRUD",
    "LFURUFLLBDLLDRBRFRBURBFRUDFRLDDDDFUBDBURLLLBFFRBUBUUFD",
    "RDDDURULUFBFRRDFRDLBLUFFDFRBDUFDURFRBBBBLLBULLRDLBUFLU",
    "DRFFUULFLUBDLRLBUUFDFFFURBLFDULDRBRRRUDRLLDDURBBBBFBDL",
    "LUULULRRFUBRLRRLDFBURFFULDBFBDUDRDDUBFDRLDRBDBFUFBBLLF",
    "BURLUDUFFDLDURRUFFFLLUFRFFBUDLRDUBBDRBLDLBDDRBLUFBBRRL",
    "URFFURDUFRBLURBLUDBRDLFBBFURDBDDLUUBFLLDLBFLUDFLDBRRFR",
    "LFULURBUUFDFBRFBBBDBLDFDLRLFBUUDLDDUDURRLFRFDRLBRBURLF",
    "FDFFUBBUBDDRLRUBBDRFRFFBFBLDRURDUFDLLRURLLDDLULULBUBFR",
    "FFDBULURDLBRFRUBURBDFLFDFULLBUFDRLLDUDRRLDBRUFLRFBBBUD",
    "UUFLUFBDBLDDDRBUBBDRDLFLFFBLRLBDUFRURBRLLULRURFFDBFRUD",
    "BBDRULFLRFDRURRUFBLBUDFBLFRFLBDDUBULDBURLRDFDFDRFBUULL",
    "BBRRULLFUFUUDRUBFFBULFFLDRDLBLUDDRFDDDULLRBBFFDRRBBRLU",
    "LDUFUURBDBLBRRBFFUDULRFUDRLRDDFDLRBFUUFLLBBRBLFFDBDRLU",
    "RURFULDDLDUBBRRFDULFBRFUULRFBUBDLFLBBRFDLUDDLUFDBBRLFR",
    "BBDDULRFDFFLURUUDDFURBFRFUBLBLDDFBRFDRUDLRUBUBLRLBLLFR",
    "BBLDUDFUBUBFBRFUFLULLDFURRRDBBDDURRDLFRRLLDRFULDLBFFUB",
    "RUUDUDUBRFFBFRLDLLFUUFFRRFRUUFRDBFBBBBLULLLDBLRDDBLDRD",
    "RDFLUBLUUFRRRRRRDBBFLBFFDLDFDBLDBLRDUFUBLUDURUFBUBLLDF",
    "UBBLULFDFRBDBRDRRFLFDBFRUFDRRBLDUBFLBFUDLULUFLDRRBLDUU",
    "LUFLURRUDBFDDRBBRUUBLRFBRLRFUDLDULDLBBBLLDDFURFURBDFFF",
    "DLUFULBUURDLDRFFFBRBFBFRDLLFBDBDDDULRRURLDLRRFFBUBUULB",
    "BFFBUDFFBLRUBRUFUDUDDFFDBUDUBRBDRRLFDLRRLUBRLLLRLBFLDU",
    "LDFFUUFRUBLRBRRFRDDURBFURLUBDLUDFFFLBDLRLLDFDUBUBBDBLR",
    "RLRFUBLFLURFURFLUDBRFLFLBBDRUFDDRUDLBUURLDFBUDBDLBDBFR",
    "RBRUULBBURBDURFLLFURFRFLBRFRDUBDDBLLDFLDLUDUUBDFRBFDFL",
    "DURDUFBLFDRURRRURDRBLUFDUDBFBLFDUFFLRLUULFDLLFLBBBBBDR",
    "RBDRUBFDLBDRFRUUFDDLUFFUFBRLLBUDLDRLFULFLDBLUFRUBBRBDR",
    "BFFLULLRLBDUBRBFFRDFUUFRDDDLRRDDLRUDRUBBLRUFFLUUDBLBBF",
    "LLDDURRDLBFBLRLFUBDRUBFDLFRUUUBDBLRUDBFFLRDLFRUBFBDRUF",
    "FRLDUDUFUBLUBRLRRLRURUFDFBDRRBDDUDFDLRFULBLFDBFUBBLFLB",
    "LDDRUUDRUBLBURRLRBFDRDFBLDUUFBLDUUBDFFRULLFFFRBDBBFLLR",
    "DRBFUFRDLFULDRUBDUFLDRFFBDDRBLFDRBULFRUBLBRLUUURLBLFBD",
    "LFBLUBDFDFRRLRUFLUBURDFFLFRFDUBDUBLBUBLULRUDDDRFRBBLDR",
    "BDLDURBBFLUDLRUDUURRULFBFFLRRBDDFBLFDBULLFLRDFFRBBURDU",
    "BDULUUFDUBBLRRDFLRURRRFBDLLBBDRDUFUDUFRLLFDULFFLBBDBFR",
    "RBDLUFUFUFUBLRFFUBRRLFFDRLLUBDBDRDBLDUFDLLLRBRUFDBRUDB",
)

for cube_state in test_cubes:
    cube = RubiksCube333(cube_state, 'URFDLB')
    cube.solve()
